# Generated by Django 2.1.5 on 2020-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('description', models.CharField(max_length=200, verbose_name='Описание страницы')),
                ('keywords', models.CharField(max_length=240, verbose_name='Ключевые слова')),
                ('content', models.TextField(blank=True, max_length=2400, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
