# Generated by Django 2.1.5 on 2020-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, verbose_name='Название')),
                ('slug', models.SlugField(max_length=224, verbose_name='URL')),
                ('image', models.ImageField(upload_to='media/album', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
