# Generated by Django 2.1.5 on 2020-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20200801_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
