# Generated by Django 2.1.5 on 2020-08-01 16:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20200801_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=600, verbose_name='Описание'),
        ),
    ]
